### ISSUE TITLE
put lib directly in the repo?

### ISSUE THREAD

**Issue by thedavidmeister** [maidsafe/rust_sodium#102]
the build step that downloads the tarballs is a source of sporadic build failures for us

we see it both on CI and developing locally

occasionally something will go wrong in the download and the hash will be incorrect, failing the build in a very cryptic way

given that only one version at a time is supported anyway (1.0.16 atm) why not simply include the extracted tarball in this repo, or setup a git submodule or something?

**Comment by thedavidmeister** [comment]
![image](https://user-images.githubusercontent.com/629710/55403168-f4b2d600-55a0-11e9-806e-00987c8b4309.png)

here is a screenshot of this crashing our production release build/deployment

**Comment by progval** [comment]
this is also an issue for CIs that block Internet access at build time, like docs.rs. https://github.com/rust-lang/docs.rs/issues/542

**Comment by S-Coyle** [comment]
The rust_sodium crate is no longer maintained by MaidSafe, you should check whether it is actively maintained on Subspace as per the readme, or switch to a modern alternative.
