### ISSUE TITLE
CI builds should cover all platforms with SHA256 constants

### ISSUE THREAD

**Issue by thedavidmeister** [maidsafe/rust_sodium#103]
see https://github.com/maidsafe/rust_sodium/issues/99

currently:

```rust
#[cfg(target_env = "msvc")] // libsodium-<VERSION>-msvc.zip
const SHA256: &'static str = "0580d54f57594a7cb493607cec6e7045369fb67d43623491523781e901589948";
```

is not covered by any tests on CI

the other hashes are covered

**Comment by S-Coyle** [comment]
The rust_sodium crate is no longer maintained by MaidSafe, you should check whether it is actively maintained on Subspace as per the readme, or switch to a modern alternative.
