### ISSUE TITLE
Support for Argon2 ?

### ISSUE THREAD

**Issue by gendx** [maidsafe/rust_sodium#44]
The Argon2 password hashing algorithm has been in libsodium since 1.0.9 (released 2 Apr 2016), and it is now recommended over scrypt https://download.libsodium.org/doc/password_hashing/
Is there any plan to support it in rust_sodium ?

**Comment by Fraser999** [comment]
There is a [PR to sodiumoxide](https://github.com/dnaq/sodiumoxide/pull/194) which provides this.  Assuming that makes it into master there, we'll likely downstream it here.  If it gets rejected, we can revisit other options at that point.

**Comment by S-Coyle** [comment]
The rust_sodium crate is no longer maintained by MaidSafe, you should check whether it is actively maintained on Subspace as per the readme, or switch to a modern alternative.
