### ISSUE TITLE
Sodiumoxide tracking policy

### ISSUE THREAD

**Issue by dbrgn** [maidsafe/rust_sodium#47]
Do you have any policy regarding tracking of changes from sodiumoxide?

For example, [here](https://github.com/dnaq/sodiumoxide/pull/172) is a feature that was recently added to sodiumoxide that I'd like to see in rust_sodium as well.

Do you plan on including sodiumoxide changes into rust_sodium from time to time, or would it be better to create a standalone pull request with the functionality?

**Comment by Fraser999** [comment]
We have been periodically pulling changes in from sodiumoxide, but not to any fixed schedule.  I hope to get a chance to look at updating again soon, but unless any are critical, this task could get pushed back down the queue unfortunately.

**Comment by dbrgn** [comment]
Ok, but if that is the plan there's no use in duplicating functionality that's present in sodiumoxide :)

**Comment by Fraser999** [comment]
Yes - I try to avoid just duplicating the functionality and actually cherry-pick commits from sodiumoxide (even though they almost always have conflicts and need fixed up) so that the original authors appear in our repo's history.
