### ISSUE TITLE
Upgrade to libsodium 1.0.15

### ISSUE THREAD

**Issue by dbrgn** [maidsafe/rust_sodium#52]
There are a few new releases of libsodium available (current version depends on 1.0.12). [Changelog](https://github.com/jedisct1/libsodium/blob/master/ChangeLog)

Upgrading to 1.0.14 or later will also fix #16.

**Comment by nshtg** [comment]
Newest version is now 1.0.16

**Comment by dbrgn** [comment]
Two interesting changes in 1.0.14:

- iOS binaries should now be compatible with WatchOS and TVOS.
- WebAssembly is now officially supported.

**Comment by nshtg** [comment]
@Fraser999 @Viv-Rajkumar ?

**Comment by zack-emmert** [comment]
Any update?

**Comment by Fraser999** [comment]
This has been addressed in #60 and has been published to crates.io as version 0.9.0 now.
