### ISSUE TITLE
windows build failed,use msys2

### ISSUE THREAD

**Issue by llgoer** [maidsafe/rust_sodium#63]
--- stderr
thread 'main' panicked at '
"powershell" "-Command" "If ($PSVersionTable.PSVersion.Major -lt 4) { exit 1 }"

You must have Powershell v4.0 or greater installed.

**Comment by Fraser999** [comment]
This should have been fixed by #55 - can you confirm you're using the latest version of rust_sodium and rust_sodium-sys please?
