### ISSUE TITLE
Build requires openssl

### ISSUE THREAD

**Issue by Aceeri** [maidsafe/rust_sodium#78]
Seems that because of the `reqwest` dependency for building, it also pulls in hyper-tls which uses openssl which is kind of unfortunate.

**Comment by jacderida** [comment]
#83 addresses this.

We discussed on Slack and it was agreed we could resolve based on the fact that we can build with OpenSSL 1.1.1. I verified this on an Ubuntu 14.04 VM:
Initial version of `openssl`:
```
vagrant@ubuntu-trusty-rust-slave:~/openssl-1.1.1$ openssl version
OpenSSL 1.0.1f 6 Jan 2014
```
Upgrade as per [these instructions](https://grumpygeekwrites.wordpress.com/2017/12/10/upgrade-openssl-on-ubuntu-14-04-2-lts-x64/) (with an additional fix from [here](https://github.com/openssl/openssl/issues/3993)):
```
vagrant@ubuntu-trusty-rust-slave:~$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```

Run `cargo build` for rust_sodium:
```
Compiling rust_sodium-sys v0.10.1 (file:///home/jenkins/rust_sodium/rust_sodium-sys)
warning: unused import: `Read`
  --> rust_sodium-sys/build.rs:21:23
   |
21 | use std::io::{Cursor, Read};
   |                       ^^^^
   |
   = note: #[warn(unused_imports)] on by default

   Compiling rust_sodium v0.10.1 (file:///home/jenkins/rust_sodium)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 26s
```
