### ISSUE TITLE
mention in the readme that `build-essential` is build essential

### ISSUE THREAD

**Issue by thedavidmeister** [maidsafe/rust_sodium#98]
this error:

```
= note: /usr/bin/ld: /tmp/rustc.ZbjniGJ7D9Ug/librust_sodium_sys-24ee5a8b5f6825c1.rlib(libsodium_la-aead_chacha20poly1305.o): relocation R_X86_64_PC32 against symbol `cr
ypto_aead_chacha20poly1305_encrypt_detached' can not be used when making a shared object; recompile with -fPIC
```

can appear when working with neon on linux even with pie disabled if `build-essential` is not installed

the readme implies (imo) that `build-essential` is only needed for cross compiling but it can show up in other edge cases it seems

unfortunately the linker error is _very_ cryptic, it took me a long time to figure out that `-fPIC` is a red herring and that i was actually missing an `apt-get` dependency (newer `gcc` or something?)

**Comment by thedavidmeister** [comment]
related https://github.com/wireapp/libsodium-neon/issues/15

**Comment by S-Coyle** [comment]
The rust_sodium crate is no longer maintained by MaidSafe, you should check whether it is actively maintained on Subspace as per the readme, or switch to a modern alternative.
